import '~/styles/globals.css'

import { Provider } from 'jotai'

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="zh-Hans" suppressHydrationWarning className="h-full">
      <body className="h-full">
        {
          // eslint-disable-next-line @eslint-react/dom/no-dangerously-set-innerhtml
          <script dangerouslySetInnerHTML={{ __html: `!function(){var e=window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches,t=localStorage.getItem("use-dark")||'"system"';('"dark"'===t||e&&'"light"'!==t)&&document.documentElement.classList.toggle("dark",!0)}();` }} />
        }
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
